sudo: required

language: go

arch:
  packages:
    - go
    # - xorg-server-xwayland
    - wayland
    # - xcb-util-image
    # - pango
    # - cairo
    # - gdk-pixbuf2
    - wlc-git
  script:
    # Fix for https://github.com/niemeyer/gopkg/issues/50
    - git config --global http.https://gopkg.in.followRedirects true
    - go get github.com/mattn/goveralls
    - make deps
    # - make check
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
